"""
Django settings for bookmanage project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print('~~~~~~~~~写法重新python manage.py runserver，运行settings.py文件是没用的~~~~~~~~~~~~~')
print(__file__) #查看当前文件的绝对路径
# D:\Study2\django-base\bookmanage\bookmanage\settings.py
print(os.path.abspath(__file__)) #查看当前文件的绝对路径
# D:\Study2\django-base\bookmanage\bookmanage\settings.py
print(os.path.dirname(os.path.abspath(__file__)) ) #查看当前文件绝对路径的上一级文件名称路径
#D:\Study2\django-base\bookmanage\bookmanage
print(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))#查看当前文件绝对路径的文件名称路径的上一级文件路径
#D:\Study2\django-base\bookmanage


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#k%p_ckn0ksprbj=x#!9etpijj#kyuk_t)fm$nq$me(c0x^hs%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#默认启动django的服务地址是：127.0.0.1:8000
#“*”可以使所有的网址都能访问Django项目了，不建议不要使用*通配符去配置，另外当DEBUG设置为False的时候必须配置这个配置，否则会抛出异常。
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'book'  # 注册/安装子应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookmanage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmanage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'#django页面改成中文#en-us默认django页面是英文

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#访问静态文件的路由
# STATIC_URL = '/static/'
STATIC_URL = '/static/'
#告诉系统静态文件的路径放在那里了
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]